import React from 'react';
import { motion } from 'motion/react';
import { 
  Book, 
  ArrowLeft, 
  HelpCircle, 
  MessageSquare, 
  Zap, 
  Settings, 
  Layers 
} from 'lucide-react';

interface DocsPageProps {
  onBack: () => void;
}

export const DocsPage: React.FC<DocsPageProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-black text-white font-sans selection:bg-red-500/30">
      {/* Header */}
      <header className="h-16 border-b border-white/5 flex items-center justify-between px-6 sticky top-0 bg-black/80 backdrop-blur-md z-50">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 hover:bg-white/5 rounded-lg transition-colors">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex items-center gap-2">
            <Book className="w-5 h-5 text-red-500" />
            <span className="font-bold tracking-tight uppercase">PRDLY_DOCS</span>
          </div>
        </div>
        <div className="text-[10px] font-mono text-white/40 uppercase tracking-widest hidden sm:block">
          System Documentation v2.0
        </div>
      </header>

      <main className="max-w-4xl mx-auto py-16 px-6">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-12"
        >
          <section>
            <h1 className="text-4xl font-display font-bold mb-6">Dokumentasi Sistem</h1>
            <p className="text-lg text-white/60 leading-relaxed">
              Selamat datang di pusat dokumentasi PRDLY. Sistem ini dirancang untuk membantu Product Manager 
              menghasilkan spesifikasi teknis berkualitas tinggi menggunakan kecerdasan buatan tingkat lanjut.
            </p>
          </section>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 bg-white/5 border border-white/10 rounded-2xl">
              <Zap className="w-6 h-6 text-red-500 mb-4" />
              <h3 className="font-bold mb-2">Pro Reasoning Engine</h3>
              <p className="text-sm text-white/50">
                Mengaktifkan mode reasoning akan memicu model AI untuk melakukan analisis mendalam 
                sebelum memberikan jawaban, sangat cocok untuk arsitektur kompleks.
              </p>
            </div>
            <div className="p-6 bg-white/5 border border-white/10 rounded-2xl">
              <Layers className="w-6 h-6 text-red-500 mb-4" />
              <h3 className="font-bold mb-2">Structure Standards</h3>
              <p className="text-sm text-white/50">
                PRD yang dihasilkan mencakup 18 section standar industri termasuk User Flow, 
                API Specs, Database Models, dan Compliance.
              </p>
            </div>
          </div>

          <section className="space-y-6">
             <h2 className="text-2xl font-bold flex items-center gap-3">
               <HelpCircle className="w-6 h-6 text-red-500" />
               Cara Penggunaan
             </h2>
             <div className="prose prose-invert max-w-none text-white/70">
               <ol className="space-y-4">
                 <li>
                   <strong>Input Ide:</strong> Masukkan deskripsi singkat produk Anda di kolom input utama. 
                   Gunakan bahasa Indonesia atau Inggris.
                 </li>
                 <li>
                   <strong>Pilih Mode:</strong> Gunakan "Standard" untuk kecepatan, atau "Pro Reasoning" 
                   untuk kedalaman analisis infrastruktur.
                 </li>
                 <li>
                   <strong>Analisis Output:</strong> Perhatikan panel "Reasoning" untuk melihat bagaimana AI 
                   berpikir sebelum menghasilkan PRD.
                 </li>
                 <li>
                   <strong>Export:</strong> Simpan hasil kerja Anda dalam format Markdown, PDF, atau DOCX.
                 </li>
               </ol>
             </div>
          </section>

          <section className="p-8 bg-red-500/10 border border-red-500/20 rounded-3xl">
             <div className="flex items-start gap-4">
               <div className="p-2 bg-red-500 rounded-lg shrink-0">
                 <MessageSquare className="w-5 h-5 text-white" />
               </div>
               <div>
                 <h4 className="font-bold mb-1">Generated by AI Gemini</h4>
                 <p className="text-sm text-white/60 italic">
                   Seluruh document PRD di sistem ini dihasilkan melalui model AI Gemini-3-Flash 
                   yang telah dioptimasi untuk penulisan teknis profesional.
                 </p>
               </div>
             </div>
          </section>

          <div className="pt-12 border-t border-white/5 text-center">
            <p className="text-[10px] font-mono text-white/30 uppercase tracking-[0.2em]">
              Created By Ramdan &copy; 2026
            </p>
          </div>
        </motion.div>
      </main>
    </div>
  );
};
